version: "3"
services:
  db:
      image: couchdb:latest
      volumes:
        - ../data/couch_data/database:/opt/couchdb/data
        - ../data/couch_data/config/local.ini:/opt/couchdb/etc/local.ini
      networks:
        - yosoft-network  
      deploy:
        resources:
          limits:
            cpus: "0.30"
            memory: 256M
          reservations:
            cpus: "0.15"
            memory: 128M
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.`${WEB_SERVER_PORT}`.rule=Host(``${WEB_SERVER_PORT}`.yosoft.app`)"
          - "traefik.http.routers.`${WEB_SERVER_PORT}`.entrypoints=websecure"
          - "traefik.http.routers.`${WEB_SERVER_PORT}`.tls.certresolver=myresolver"
          - "traefik.http.services.`${WEB_SERVER_PORT}`.loadbalancer.server.port=`${WEB_SERVER_PORT}`" 
  
networks:
  yosoft-network:
    external: true